apiVersion: acmeplatform.com/v1alpha1
kind: AppClaim
metadata:
  name: simplehttpserver 
  namespace: simplehttpserver
  labels:
    app-owner: piotrzan
spec:
  id: simplehttpserver
  compositionSelector:
    matchLabels:
      type: frontend
  parameters:
    namespace: simplehttpserver
    image: 616652803683.dkr.ecr.eu-north-1.amazonaws.com/controlplane/simplehttpserver:v0.1
    host: acme-platform2.127.0.0.1.nip.io
    port: 8000
